/**
 * Managed-block merging.
 *
 * Teams already have a `CLAUDE.md` full of their own instructions, and
 * `anchor sync` must never destroy it. Generated content therefore lives inside
 * delimited markers, and everything outside them is preserved byte for byte.
 *
 * The markers are also what makes `sync` idempotent: running it twice replaces
 * the block in place rather than appending a second copy.
 */

export interface BlockMarkers {
  start: string;
  end: string;
}

/** HTML comment markers, invisible when Markdown is rendered. */
export const MARKDOWN_MARKERS: BlockMarkers = {
  start: '<!-- anchor:start -->',
  end: '<!-- anchor:end -->',
};

/** Hash comment markers, for plain-text targets such as `.cursorrules`. */
export const TEXT_MARKERS: BlockMarkers = {
  start: '# anchor:start',
  end: '# anchor:end',
};

const WARNING = 'Generated by Anchor. Edits inside this block will be overwritten.';

export interface MergeResult {
  content: string;
  /** How the generated block related to what was already in the file. */
  outcome: 'created' | 'replaced' | 'appended' | 'unchanged';
  /** Set when the existing file had a damaged marker pair. */
  warning?: string;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Wraps generated content in its markers, with a warning comment for humans. */
export function wrapBlock(generated: string, markers: BlockMarkers): string {
  const comment = markers === TEXT_MARKERS ? `# ${WARNING}` : `<!-- ${WARNING} -->`;
  return `${markers.start}\n${comment}\n\n${generated.trim()}\n\n${markers.end}`;
}

/**
 * Merges generated content into an existing file.
 *
 * The generated block is appended when the file has no markers yet, so a team's
 * own instructions keep their position at the top of the file.
 *
 * A start marker with no matching end marker is treated as damage rather than
 * as a licence to eat the rest of the file: the block is rewritten from the
 * start marker to the end of the file and a warning is returned, because
 * silently discarding whatever followed would be far worse than saying so.
 */
export function mergeManagedBlock(
  existing: string | null,
  generated: string,
  markers: BlockMarkers = MARKDOWN_MARKERS,
): MergeResult {
  const block = wrapBlock(generated, markers);

  if (existing === null || existing.trim() === '') {
    return { content: `${block}\n`, outcome: 'created' };
  }

  const startIndex = existing.indexOf(markers.start);
  if (startIndex === -1) {
    const separator = existing.endsWith('\n') ? '\n' : '\n\n';
    return { content: `${existing}${separator}${block}\n`, outcome: 'appended' };
  }

  const endIndex = existing.indexOf(markers.end, startIndex);

  if (endIndex === -1) {
    const before = existing.slice(0, startIndex);
    return {
      content: `${before}${block}\n`,
      outcome: 'replaced',
      warning: `Found \`${markers.start}\` with no matching \`${markers.end}\`. Anchor rewrote everything from the start marker to the end of the file; check the result before committing.`,
    };
  }

  const before = existing.slice(0, startIndex);
  const after = existing.slice(endIndex + markers.end.length);
  const merged = `${before}${block}${after}`;

  return {
    content: merged,
    outcome: merged === existing ? 'unchanged' : 'replaced',
  };
}

/** Extracts the generated block from a file, or `null` when there is none. */
export function extractManagedBlock(
  content: string,
  markers: BlockMarkers = MARKDOWN_MARKERS,
): string | null {
  const pattern = new RegExp(
    `${escapeRegExp(markers.start)}([\\s\\S]*?)${escapeRegExp(markers.end)}`,
  );
  const match = pattern.exec(content);
  return match?.[1]?.trim() ?? null;
}
